sudo: required
services:
  - docker

before_install:
  - docker build -t emielvdongen/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true emielvdongen/react-test npm test -- --coverage

after_success:
  - docker build -t emielvdongen/multi-client ./client
  - docker build -t emielvdongen/multi-nginx ./nginx
  - docker build -t emielvdongen/multi-server ./server
  - docker build -t emielvdongen/multi-worker ./worker
  - eho "$DOCKER_PWD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push emielvdongen/multi-client
  - docker push emielvdongen/multi-nginx
  - docker push emielvdongen/multi-server
  - docker push emielvdongen/multi-worker
